# Generated by Django 2.1.5 on 2019-05-08 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('org_name', models.CharField(max_length=200)),
                ('org_short_name', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='org_logo/')),
                ('address', models.CharField(max_length=260)),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('whatsapp', models.IntegerField(blank=True, null=True)),
                ('fax', models.CharField(max_length=50)),
                ('p_o_box', models.CharField(max_length=80)),
                ('permit_number', models.CharField(max_length=15, null=True)),
                ('permit_date', models.CharField(max_length=10, null=True)),
                ('board_members', models.TextField()),
                ('info', models.TextField()),
                ('goals', models.TextField()),
                ('projects', models.TextField()),
                ('permit', models.BooleanField(default=False)),
                ('org_links', models.URLField(blank=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('bank_account_short_info', models.TextField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('org_name',),
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=66)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=66)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='OrgType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=66)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=66)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Bank'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.City'),
        ),
        migrations.AddField(
            model_name='user',
            name='org_types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.OrgType'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.State'),
        ),
        migrations.AlterIndexTogether(
            name='user',
            index_together={('id', 'slug')},
        ),
    ]
