# Generated by Django 2.1.5 on 2019-01-26 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('first_address', models.CharField(blank=True, max_length=255)),
                ('second_address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('last_donation_date', models.DateField(default=uuid.uuid1, unique=True)),
                ('profession', models.CharField(choices=[('Student', 'Student'), ('Employer', 'Employer'), ('Unemployed', 'Unemployed'), ('Businessman', 'Businessman')], max_length=20)),
                ('blood', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age', models.IntegerField(default=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
