# Generated by Django 2.1.5 on 2019-05-08 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(upload_to='org_logo/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default=datetime.datetime(2019, 5, 8, 13, 15, 7, 724312, tzinfo=utc), upload_to='user_photo/'),
            preserve_default=False,
        ),
    ]
