# Generated by Django 2.1.5 on 2019-05-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190508_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='user_photo/', verbose_name='org_name'),
        ),
    ]
