# Generated by Django 2.2.1 on 2019-05-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190510_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinfo',
            name='slug',
            field=models.SlugField(),
        ),
    ]
