# Generated by Django 2.2.1 on 2019-05-10 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190510_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='photo',
            field=models.ImageField(blank=True, default=datetime.datetime(2019, 5, 10, 13, 17, 46, 388639, tzinfo=utc), upload_to='user_photo/'),
            preserve_default=False,
        ),
    ]
