# Generated by Django 2.1.2 on 2018-11-04 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20181027_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprofile',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalProfile',
        ),
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
    ]
