# Generated by Django 2.1.2 on 2018-11-04 19:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20181104_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_donation_date',
            field=models.DateField(default=uuid.uuid1),
        ),
    ]
