# Generated by Django 2.1.2 on 2018-11-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20181104_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_donation_date',
            field=models.DateField(null=True),
        ),
    ]
