# Generated by Django 2.1.2 on 2018-11-05 01:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20181105_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_donation_date',
            field=models.DateField(default=uuid.uuid1, unique=True),
        ),
    ]
